### ISSUE TITLE
Render screen in separate Task

### ISSUE THREAD

**Issue by caspargross** [imgag/ProgrammierPraktikum2018_Gruppe3#14]
- [ ] After zoom operation, draw screen in new Task.
- [ ] Include Monitor if Application is working

**Comment by felixWedlich** [comment]
As reference for todays´s discussion:

General Caching stuff:
Too much caching without setting VM options -Dprism.maxvram=2000M (or similar high values) end up with NullPointer [exceptions:()](https://bugs.openjdk.java.net/browse/JDK-8191183)
    - JavaFX doesnt seem to evict properly unused VRAM
    - JavaFx doesnt seem to properly evict unused RAM- 
![cache ram-usage](https://user-images.githubusercontent.com/39565595/43203817-89e6d052-901f-11e8-8646-0edabcd649e4.PNG)
 3gb usage after scrolling far in, toggling a bit, then scrolling out, having now a semi-blurry overview and no discarded old caches

Caching SPEED seems to be some sort of nondeterministic magic: Toggling Quality/Speed ends up that every2nd / every3rd SPEED setting has the visual quality of QUALITY- yet the fluidity of SPEED. All the other cached images are expected blurry stuff

General multi-thread stuff:
Updating GUI elements (even of a different stage)  require performing this action in the same FX-Application Thread("Exception in thread "Thread-9" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-9")

https://stackoverflow.com/questions/13784333/platform-runlater-and-task-in-javafx

Proposed Platform.runLater doesnt work in reality well since the entire work of the task is consisting of updating the GUI/Cache, so basically runLater just adds it onto the workload of the FX-Applcation Thread. -> CounterProductive

Note:  task.succeeded (creating a new Pane + setting caches of Children) happens even before the GUI updates the new scene correctly, making it  not possible to get notified when caching would be complete and we could swap out ViewElements

General Notes: 
Disabling Cache completely with the current readAmount of 500 is completely fluid on my system <40% cpu even when rotating/scaling fast.
1500 is acceptable aswell, if sensitivity of rotationspeed is adjusted

**Comment by caspargross** [comment]
not possible.
